[2024-06-26T11:27:09.878+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T11:27:09.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-26T11:27:09.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-26T11:27:09.943+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-06-26T11:27:09.966+0000] {taskinstance.py:2330} INFO - Executing <Task(LoadDatabaseLocal): load_db_local> on 2024-06-23 00:00:00+00:00
[2024-06-26T11:27:09.979+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=414) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T11:27:09.982+0000] {standard_task_runner.py:63} INFO - Started process 440 to run task
[2024-06-26T11:27:09.983+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'peduli_pintar_elt_all_dags', 'load_db_local', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/etl_all_dags.py', '--cfg-path', '/tmp/tmp0gb3__qn']
[2024-06-26T11:27:09.987+0000] {standard_task_runner.py:91} INFO - Job 400: Subtask load_db_local
[2024-06-26T11:27:10.063+0000] {task_command.py:426} INFO - Running <TaskInstance: peduli_pintar_elt_all_dags.load_db_local scheduled__2024-06-23T00:00:00+00:00 [running]> on host 5338995eebdf
[2024-06-26T11:27:10.411+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kelompok 5 Capstone DE' AIRFLOW_CTX_DAG_ID='peduli_pintar_elt_all_dags' AIRFLOW_CTX_TASK_ID='load_db_local' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-26T11:27:10.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T11:27:10.529+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-06-26T11:27:10.741+0000] {etl_all_operator.py:384} INFO - Connected to MySQL database 'peduli_pintar' on server 'IkaPurwanti'
[2024-06-26T11:27:10.748+0000] {etl_all_operator.py:390} INFO - Connection to MySQL with connection ID 'mysql_default' is successful.
[2024-06-26T11:27:10.750+0000] {etl_all_operator.py:509} INFO - Connection DB sukses!!!
[2024-06-26T11:27:11.157+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-06-26T11:27:14.966+0000] {etl_all_operator.py:497} INFO - Data berhasil disimpan ke tabel-tabel dalam database 'peduli_pintar'.
[2024-06-26T11:27:14.971+0000] {etl_all_operator.py:519} INFO - Data insertion completed successfully.
[2024-06-26T11:27:14.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T11:27:15.073+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=peduli_pintar_elt_all_dags, task_id=load_db_local, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240626T112709, end_date=20240626T112715
[2024-06-26T11:27:15.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T11:27:15.172+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T11:27:15.175+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
