[2024-06-23T15:10:34.641+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_all_dags_v1.load_firebase scheduled__2024-06-21T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
