[2024-06-23T15:10:35.148+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_all_dags_v1.transform_dw_schema scheduled__2024-06-21T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
